### PR TITLE
feat: added pictures align features

### PR DESCRIPTION
**Pull request by baravkareknath**
## Related resources

* #...
* #...

## Checklist

* [x] I have opened this pull request against ``master``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by baravkareknath** [comment]
Update PR title please review contribution

**Comment by fsbraun** [comment]
@baravkareknath Please, can you add a structured description of what this PR is supposed to do? 

So far, I see you have changed the alignment options in the model. How do the new options differ from the existing ones. How are these options rendered?

**Comment by baravkareknath** [comment]
Hi fsbraun thanks for your replay.
I am not changed the old alignment options in the model. Just added new options that are works like old options. New options are for float images from left to right and vice versa and set image on top and bottom. Looks as below-

# Add setting for picture alignment, renders a class or inline styles
# depending on your template setup
def get_alignment():
    alignment = getattr(
        settings,
        'DJANGOCMS_PICTURE_ALIGN',
        (
            ('left', _('Align left')),
            ('right', _('Align right')),
            ('center', _('Align center')),
            ('ltr', _('Left-to-Right')), #Newly added option
            ('rtl', _('Right-to-Left')), #Newly added option
            ('top', _('Top Aligned')), #Newly added option
            ('bottom', _('Bottom Aligned')), #Newly added option
        )
    )
    return alignment

Hopes that's options are also useful for picture alignment.

**Comment by baravkareknath** [comment]
Hi fsbraun,
Please look into patch of code and let me know about this contribution.

**Comment by fsbraun** [comment]
@baravkareknath **I still do not see how those options are rendered.** As far as I can see, the PR adds options to the plugin which do not change its behaviour.

To me, it seems a cleaner solution to provide both the `DJANGOCMS_PICTURE_ALIGN` setting and accompanying CSS on a per-project basis. 

I fear the project itself cannot make assumptions about the CSS used. Any idea on how to render those options including top and bottom alignment?

**Comment by baravkareknath** [comment]
Hi fsbraun, As per your suggestion I will add CSS file in the same and share new patch of CSS.

**Comment by baravkareknath** [comment]
Hi fsbraun,
As per your suggestion i am pull new request and wants to submit it but Invalid PR title error occurred so can you suggest me which PR Title like docs, style or any others is suitable for "Added image align options example."

**Pull request closed without merging**
